application: party-page
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: favidon.ico
- url: /img
  static_dir: img
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /ext
  static_dir: ext
- url: /test.*
  script: gaeunit.py
- url: /.*
  script: main.py
