application: party-page
version: 1-1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico
- url: /img
  static_dir: img
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /ext
  static_dir: ext
- url: /test.*
  script: gaeunit.py
- url: /.*
  script: main.py
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
